// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mojiigakhvhrcrvrjvfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vamlpZ2FraHZocmNydnJqdmZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTY2ODYsImV4cCI6MjA2NDYzMjY4Nn0.Pzen2TLZfiuuuoNp6ScXQWPKazPAr2XTa_Kb7RL5BhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);